version: "3.9"

services:
  php-env:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user2'
      MYSQL_PASSWORD: 'user2123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1